var async = require('async');
module.exports = {
    extend : "apostrophe-pieces",
    name : "dynamic-table",
    label : "Dynamic Table",
    alias : "dynamicTable",
    seo: false,
    openGraph: false,
    moogBundle : {
        modules: ['dynamic-table-schemas', 'dynamic-table-widgets' , 'dynamic-table-utils'],
        directory: 'lib/modules'
    },
    beforeConstruct : function(self,options){
        // Lean or Non-Lean Assets to decide which fields to use 
        var originalFields = [];
        if (options.apos.assets.options.lean) {
            originalFields = [
                {
                    name: "ajaxOptions",
                    label: "Ajax Options",
                    type: "string",
                    textarea: true,
                    htmlHelp: `Example :
            <br><br><pre><code style="font-family: monospace;background-color: #EEE;padding: 10px;font: 300 12px monospace;display: block;">ajax: {
    url: "some/url/data.txt", // url to remote data
    content: {
        type: "csv", // specify the content
    },
    load: function(xhr) {
        // process and return the response data
    }
}</code></pre>You can refer here for more info : <a href="https://github.com/fiduswriter/Simple-DataTables/wiki/ajax" target="_blank">DataTables Vanilla JS Ajax Data Source</a><br>`
                }
            ];
        } else {
            originalFields = [
                {
                    name: "ajaxOptions",
                    label: "Ajax Options",
                    type: "string",
                    textarea: true,
                    htmlHelp: `Example :
            <br><br><pre><code style="font-family: monospace;background-color: #EEE;padding: 10px;font: 300 12px monospace;display: block;">{
  ajax: "data/arrays.txt"
}</code></pre>You can refer here for more info : <a href="https://datatables.net/examples/ajax/" target="_blank">DataTables JQuery Ajax Data Source</a><br>`
                }
            ]
        }
        options.addFields = [
            {
                name : "title",
                type : "string",
                label : "Title",
                required : true
            },
            {
                name: 'row',
                label: 'Number of Row(s)',
                type: 'integer'
            },
            {
                name: 'column',
                label: 'Number of Column(s)',
                type: 'integer'
            },
            {
                name: "data",
                label: "Custom Data",
                type: "string",
                textarea: true,
                help: "This field is auto generated by your row & column input."
            }
        ].concat(options.addFields || []);

        // Combine fields
        options.addFields = options.addFields.concat(originalFields);

        options.arrangeFields = [
            {
                name: "table",
                label: "Custom Table",
                fields: ["row", "column", "data"]
            },
            {
                name: "ajax",
                label: "Ajax Table",
                fields: ["ajaxOptions"]
            },
            {
                name: "settings",
                label: "Settings",
                fields: ["title"],
                last: true
            }
        ].concat(options.arrangeFields || []);
    },
    afterConstruct : function(self){
        self.dynamicTableSchemas();
    },
    construct : function(self,options){
        var superPushAssets = self.pushAssets;
        self.dynamicTableSchemas = function(){
            self.tableSchemas = self.apos.schemas.subset(self.schema, ["row", "column" , "data", "ajaxOptions"])
            self.tableSchemasGroup = self.apos.schemas.toGroups(self.schema);
        };

        self.apos.permissions.add({
            value: 'edit-dynamic-table',
            label: 'Edit Dynamic Table'
        });

        // Add Submit Route for pieces insert
        self.route('post', "submit", function(req,res){
            return self.submitTables(req, function(err){
                if(err){
                    return res.send({
                        status : "error",
                        message : err
                    })
                }

                return res.send({
                    status : "success",
                    message : "Success !"
                })
            })
        })

        self.route("post", "update", function(req,res){
            return self.updateTables(req, function (err) {
                if (err) {
                    return res.send({
                        status: "error",
                        message: err
                    })
                }

                return res.send({
                    status: "success",
                    message: "Success !"
                })
            })
        })

        self.updateTables = function(req, callback){
            return async.series([
                convert,
                update
            ],callback);

            function convert(callback) {
                var piece = {};
                return self.apos.schemas.convert(req, self.schema, null, req.body, piece , callback);
            }

            function update(callback){
                return self.update(req, piece, {permissions : false } , callback);
            }
        }

        self.submitTables = function(req , callback){
            return async.series([
                convert,
                insert
            ],callback);

            function convert(callback){
                var piece = {};
                return self.apos.schemas.convert(req, self.schema, null , req.body, piece, callback);
            }

            function insert(callback){
                return self.insert(req, piece , { permissions : false } , callback);
            }
        }
    }
}