#!/bin/bash
DIR="apostrophe-test"
MODULE_NAME='dynamic-table'
MYDIR="node_modules/$MODULE_NAME"
FILESTOCOPY=("collections" "views" "public" "index.js" "package.json" "callbackFields.js" "sub-modules")
TESTCOPY=("tests")
TEMPSERVER="server.js"

copy_module (){
    if [ "$(ls -A $MYDIR && du $MYDIR)" ];then
        echo "$MYDIR file already created"
    else
        mkdir "$MYDIR"
    fi

    if [[ "$(declare -p FILESTOCOPY)" =~ "declare -a" ]];then
        echo "Running Loop"
        for files in ${!FILESTOCOPY[@]}; do
            echo "Copying ${FILESTOCOPY[$files]} to $MYDIR directory"
            cp -r ../${FILESTOCOPY[$files]} "$MYDIR"
        done
    fi

    if [[ "$(declare -p TESTCOPY)" =~ "declare -a" ]];then
        for files in ${!TESTCOPY[@]}; do
            echo "Copying ${TESTCOPY[$files]} to $DIR directory"
            cp -r ../${TESTCOPY[$files]} .
        done
    fi
    echo "Your $MODULE_NAME copied to $MYDIR"
}

temp_nighwatch(){
    echo "Copying temporary server.js onto apostrophe-nightwatch-tools due to bug issue"
    cp -r ../tests/"$TEMPSERVER" node_modules/apostrophe-nightwatch-tools
}

checking_mongodump(){
    if [ "$(ls -A mongodump && du mongodump)" ];then
        echo "mongodump folder already created"
    else
        mkdir mongodump/
    fi
}

# Checking Apostrophe CLI installed in a system
if [ "$(apostrophe --version)" ];then
    echo "Apostrophe CLI existed"
    printf "*************************\n\n"
else
    echo "Installing Apostrophe CLI"
    npm i apostrophe-cli -g
    printf "*************************\n\n"
fi
# init
# Look for apostrophe-test directory
# script $(ls -A $DIR) checking directory
# script $(du $DIR) check file size existed
if [ "$(ls -A $DIR && du $DIR)" ];then
    echo "apostrophe-test folder already existed"
    printf "\n\nCopy app.js to testing directory\n"
    printf "*******************************\n"
    cp -v tests/apos/app.js /"$DIR" &&
    printf "*******************************\n\n"
    cd "$DIR"
    printf "Re-installed Packaged to keep updated \n"
    npm install
    printf "\nPackage Installed."
    echo "Copy our module to $PWD inside node_modules to test"
    copy_module
    temp_nighwatch
    checking_mongodump
else
    echo "Creating apostrophe-test folder"
    apostrophe create-project "$DIR"
    printf "\n\nCopy app.js to testing directory\n"
    printf "*******************************\n"
    cp -v tests/apos/app.js "$DIR" &&
    printf "*******************************\n\n"
    cd "$DIR"
    echo "Entering current directory $PWD"
    echo "Apostrophe Boilerplate created"
    echo "Installing packages"
    npm install
    printf "******************************\n\n"
    printf "Installing package:\n\n-nightwatch\n-apostrophe-nightwatch-tools\n-chromedriver@80.0.2\n-geckodriver\n-selenium-server\n-apostrophe-workflow\n\n\n"
    printf "*******************************\n\n"
    npm install --save-dev nightwatch apostrophe-nightwatch-tools chromedriver@80.0.2 geckodriver selenium-server && npm install --save apostrophe-workflow
    printf "Copy our module to $PWD inside node_modules to test\n\n"
    copy_module
    temp_nighwatch
    checking_mongodump
fi

# Running Test
echo "** running test from"
echo $PWD
echo "*******************************\n\n"
echo "\n\nBegin Test\n\n"
./node_modules/.bin/nightwatch ./tests/scenarios/ --config ./tests/nightwatch.conf.js -e local &&
echo "TEST ENDED"