module.exports = {
    extend : "apostrophe-widgets",
    label : "Table Widget",
    scene : "user",
    beforeConstruct : function(self,options){
        options.addFields =  [
            {
                name: 'row',
                label: 'Number of Row(s)',
                type: 'integer'
            },
            {
                name : 'column',
                label : 'Number of Column(s)',
                type : 'integer'
            },
            {
                name: "ajaxOptions",
                label: "Ajax Options",
                type: "string",
                textarea: true,
                htmlHelp: `Example :
            <br><br><pre><code style="font-family: monospace;background-color: #EEE;padding: 10px;font: 300 12px monospace;display: block;">{
  "ajax": "data/arrays.txt"
}</code></pre>You can refer here for more info : <a href="https://datatables.net/examples/ajax/" target="_blank">DataTables JS Ajax Data Source</a><br>NOTE : You must use double quote string on your field name to make it work, for instance : <code>\"ajax\" : "<ajaxUrl>"</code>`
            },
            {
                name: "data",
                label: "Custom Data",
                type: "string",
                textarea : true,
                help : "This field is auto generated by your row & column input."
            }
        ].concat(options.addFields || []);
        options.arrangeFields = [
            {
                name : "table",
                label : "Custom Table",
                fields : ["row" , "column" , "data"]
            },
            {
                name: "ajax",
                label: "Ajax Table",
                fields: ["ajaxOptions"]
            },
            {
                name : "settings",
                label : "Settings",
                fields : [],
                last : true
            }
        ].concat(options.arrangeFields || []);
    },
    construct : function(self,options){
        var superPushAssets = self.pushAssets;

        // Override but pass extra data (data.something)
        self.output = function (widget, options) {
            return self.partial(self.template, {
                widget: widget,
                options: options,
                manager: self,
                // Pass to widget.html
                table: self.myData
            });
        };

        self.route("post", "submit", function(req,res){
            if(!req.body.table){
                return res.send({
                    status : "error",
                    message : "Data Not Received"
                })
            }

            // Get data
            self.myData = req.body.table

            return res.send({
                status : "success",
                message : "Data Received"
            })
        })

        self.pushAssets = function(){
            superPushAssets();

            self.pushAsset('script', 'editor', {
                when : "user"
            });

            self.pushAsset('script', 'datatables$/datatables.min', {
                when: "always"
            });

            self.pushAsset('stylesheet', 'jquery/datatables.min', {
                when: "always"
            })

            if(self.apos.assets.options.lean){
                if(options.player){
                    self.pushAsset('script', 'datatablesJS/datatables.min', {
                        when: "lean"
                    });

                    self.pushAsset('script', 'lean', {
                        when: "lean"
                    });

                    self.pushAsset('stylesheet', 'vanillaJS/datatables.min', {
                        when: "lean"
                    })
                }
            }
        }

        // Extend Options to get on browser apostrophe-widgets JS
        var superGetCreateSingletonOptions = self.getCreateSingletonOptions;
        self.getCreateSingletonOptions = function (req) {
            var options = superGetCreateSingletonOptions(req);
            options.table = self.myData;
            return options;
        };
    }
}